name: CI

on:
  push:
    branches: [ "production", "staging", "development" ]
  pull_request:
    branches: [ "production", "staging", "development" ]

jobs:
  UnitTest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run Jest tests
        run: npm test
